ARG version
# 配置基础镜像
FROM registry.cn-sh-01.sensecore.cn/ai-expert-service/lazyllm:${version}

# 安装依赖
RUN set -ex \
    && apt-get update \
    && apt-get install -y zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -u 1000 -m -s /usr/bin/zsh  -d "/home/mnt/platform_ci"  "platform_ci"

ENTRYPOINT ["/usr/bin/zsh"]

USER platform_ci

WORKDIR /home/mnt/platform_ci