ARG version
# 配置基础镜像
FROM registry.cn-sh-01.sensecore.cn/ai-expert-service/lazyllm:${version}

# 安装依赖
RUN set -ex \
    && apt-get update \
    && apt-get install -y zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -u 1087 -m -s /usr/bin/zsh -d "/home/mnt/xufanghan"  "xufanghan"

ENTRYPOINT ["/usr/bin/zsh"]

USER xufanghan

WORKDIR /home/mnt/xufanghan
