# 配置基础镜像
FROM registry.cn-sh-01.sensecore.cn/ai-expert-service/lazyllm:cuda12.1.0-cudnn8-ubuntu22.04_0703

# 安装依赖
RUN set -ex \
    && useradd -u 1090 -m -d "/home/mnt/yewentao"  "yewentao"

USER yewentao

WORKDIR /home/mnt/yewentao