ARG version
# 配置基础镜像
FROM registry.cn-sh-01.sensecore.cn/ai-expert-service/lazyllm:${version}

# 安装依赖
RUN set -ex \
    && useradd -u 1094 -m -d "/home/mnt/zhangyongchao"  "zhangyongchao"

USER zhangyongchao

WORKDIR /home/mnt/zhangyongchao