ARG version
# 配置基础镜像
FROM registry.cn-sh-01.sensecore.cn/ai-expert-service/lazyllm:$version

ENV PATH=/home/mnt/test_user/Test/miniconda3/bin:/usr/local/redis-stack-server-7.2.0-v10/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# 安装依赖
RUN set -ex \
    && apt-get update \
    && apt-get install -y zsh iputils-ping \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -u 9998 -m -s /usr/bin/zsh -d "/home/mnt/test_user"  "test_user"

ENTRYPOINT ["/usr/bin/zsh"]

USER test_user

WORKDIR /home/mnt/test_user
